spring:
  application:
    name: ms-yanki
  profiles:
    active:
      - dev #(2)
  config:
    import: optional:configserver:http://localhost:9010
    #import: optional:configserver:http://config-server:9010
  cloud:
    config:
      profile: dev